import type { SnagElement } from "./protocol";

const MAX_TEXT_LENGTH = 120;
const MAX_ATTRIBUTE_LENGTH = 120;
const MAX_SELECTOR_DEPTH = 5;
const MAX_COMPONENT_STACK = 5;
const MAX_FIBER_HOPS = 60;

const ATTRIBUTE_NAMES = [
  "data-testid",
  "data-test",
  "data-cy",
  "role",
  "aria-label",
  "name",
  "type",
  "placeholder",
  "href",
  "alt",
  "title",
  "for",
  "class",
];

const TEST_ID_ATTRIBUTES = ["data-testid", "data-test", "data-cy"];

/** Ids generated by React `useId`, Radix, Headless UI, MUI, etc. — not stable across renders. */
const GENERATED_ID_PATTERN = /^:|^(radix|headlessui|mui|react-aria|rc|downshift)[-_]|\d{3,}/i;

/** Framework plumbing that never helps locate product code. */
const IGNORED_COMPONENT_PATTERN =
  /^(Fragment|Suspense|StrictMode|Profiler|Anonymous|ErrorBoundary\w*|\w*Provider|\w*Context|\w*Consumer|Router|AppRouter|InnerLayoutRouter|OuterLayoutRouter|RenderFromTemplateContext|ScrollAndFocusHandler|InnerScrollAndFocusHandler|LoadingBoundary|RedirectBoundary|RedirectErrorBoundary|NotFoundBoundary|HTTPAccessFallbackBoundary|HTTPAccessFallbackErrorBoundary|DevRootHTTPAccessFallbackBoundary|SegmentViewNode|HotReload|ReactDevOverlay|SnagOverlay)$/;

/** React-internal / dependency frames to skip when reading a debug stack. */
const LIBRARY_FRAME_PATTERN =
  /node_modules|\.vite\/deps|react-dom|react[-_]jsx|react-stack-top-frame|\/react\.|_next\/static\/chunks\/(framework|main|webpack)/;

function truncate(value: string, max: number): string {
  if (value.length <= max) return value;
  return `${value.slice(0, max - 1)}…`;
}

function collapse(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function escapeIdent(value: string): string {
  return typeof CSS !== "undefined" && CSS.escape ? CSS.escape(value) : value;
}

function anchorSelector(element: Element): string | null {
  for (const name of TEST_ID_ATTRIBUTES) {
    const value = element.getAttribute(name);
    if (value) return `[${name}="${value.replace(/"/g, '\\"')}"]`;
  }
  const id = element.id;
  if (id && !GENERATED_ID_PATTERN.test(id)) {
    const selector = `#${escapeIdent(id)}`;
    try {
      if (document.querySelectorAll(selector).length === 1) return selector;
    } catch {
      // Unusual ids can still produce invalid selectors; fall through.
    }
  }
  return null;
}

function segmentSelector(element: Element): string {
  const tag = element.tagName.toLowerCase();
  const parent = element.parentElement;
  if (!parent) return tag;
  const sameTag = Array.from(parent.children).filter(
    (child) => child.tagName === element.tagName,
  );
  if (sameTag.length === 1) return tag;
  return `${tag}:nth-of-type(${sameTag.indexOf(element) + 1})`;
}

export function buildSelector(element: Element): string {
  const parts: string[] = [];
  let node: Element | null = element;
  while (
    node &&
    node !== document.body &&
    node !== document.documentElement &&
    parts.length < MAX_SELECTOR_DEPTH
  ) {
    const anchor = anchorSelector(node);
    if (anchor) {
      parts.unshift(anchor);
      break;
    }
    parts.unshift(segmentSelector(node));
    node = node.parentElement;
  }
  return parts.join(" > ") || element.tagName.toLowerCase();
}

function readText(element: Element): string | undefined {
  // Form controls may hold user data; describe them by attributes only.
  if (
    element instanceof HTMLInputElement ||
    element instanceof HTMLTextAreaElement ||
    element instanceof HTMLSelectElement
  ) {
    return undefined;
  }
  const raw =
    element instanceof HTMLElement ? element.innerText : element.textContent ?? "";
  const text = collapse(raw ?? "");
  return text ? truncate(text, MAX_TEXT_LENGTH) : undefined;
}

function sanitizeHref(href: string): string {
  try {
    const url = new URL(href, window.location.href);
    if (url.protocol !== "http:" && url.protocol !== "https:") return url.protocol;
    return url.origin === window.location.origin
      ? url.pathname
      : `${url.origin}${url.pathname}`;
  } catch {
    return "";
  }
}

function readAttributes(element: Element): Record<string, string> | undefined {
  const attributes: Record<string, string> = {};
  for (const name of ATTRIBUTE_NAMES) {
    const raw = element.getAttribute(name);
    if (!raw) continue;
    const value = collapse(name === "href" ? sanitizeHref(raw) : raw);
    if (value) attributes[name] = truncate(value, MAX_ATTRIBUTE_LENGTH);
  }
  return Object.keys(attributes).length > 0 ? attributes : undefined;
}

// ---- React fiber introspection (best effort; shapes differ across versions) ----

interface Fiber {
  type: unknown;
  return: Fiber | null;
  _debugSource?: { fileName?: string; lineNumber?: number; columnNumber?: number } | null;
  _debugStack?: unknown;
}

function getFiber(element: Element): Fiber | null {
  for (const key of Object.keys(element)) {
    if (key.startsWith("__reactFiber$") || key.startsWith("__reactInternalInstance$")) {
      return (element as unknown as Record<string, Fiber>)[key] ?? null;
    }
  }
  return null;
}

function componentName(type: unknown, depth = 0): string | null {
  if (!type || typeof type === "string" || depth > 3) return null;
  if (typeof type === "function") {
    const fn = type as { displayName?: string; name?: string };
    return fn.displayName || fn.name || null;
  }
  if (typeof type === "object") {
    const wrapper = type as { displayName?: string; render?: unknown; type?: unknown };
    if (wrapper.displayName) return wrapper.displayName;
    if (wrapper.render) return componentName(wrapper.render, depth + 1);
    if (wrapper.type) return componentName(wrapper.type, depth + 1);
  }
  return null;
}

function isUsefulName(name: string): boolean {
  // One- or two-letter names are almost always minified production builds.
  return name.length > 2 && !IGNORED_COMPONENT_PATTERN.test(name);
}

function readComponentStack(fiber: Fiber): string[] {
  const names: string[] = [];
  let node: Fiber | null = fiber.return;
  let hops = 0;
  while (node && names.length < MAX_COMPONENT_STACK && hops < MAX_FIBER_HOPS) {
    const name = componentName(node.type);
    if (name && isUsefulName(name) && names[names.length - 1] !== name) {
      names.push(name);
    }
    node = node.return;
    hops += 1;
  }
  return names;
}

function normalizeSourceFile(url: string): string {
  let file = url;
  try {
    const parsed = new URL(url);
    file = decodeURIComponent(parsed.pathname);
  } catch {
    file = url.split("?")[0] ?? url;
  }
  return file.replace(/^\/@fs(?=\/)/, "").replace(/^\/\.\//, "/");
}

/** Parse the first app-code frame from a V8 / SpiderMonkey / JSC stack string. */
export function parseSourceFromStack(stack: string): SnagElement["source"] | undefined {
  for (const rawLine of stack.split("\n")) {
    const line = rawLine.trim();
    if (!line) continue;
    let location = line;
    const open = line.lastIndexOf("(");
    if (open >= 0 && line.endsWith(")")) {
      location = line.slice(open + 1, -1);
    } else if (line.startsWith("at ")) {
      location = line.slice(3);
    } else {
      const at = line.indexOf("@");
      if (at >= 0 && !line.slice(0, at).includes("/")) location = line.slice(at + 1);
    }
    const match = location.match(/^(.*):(\d+):(\d+)$/);
    if (!match) continue;
    const [, url, lineNumber, columnNumber] = match;
    if (!url || LIBRARY_FRAME_PATTERN.test(url)) continue;
    return {
      file: truncate(normalizeSourceFile(url), 300),
      line: Number(lineNumber),
      column: Number(columnNumber),
    };
  }
  return undefined;
}

function readSource(fiber: Fiber): SnagElement["source"] | undefined {
  let node: Fiber | null = fiber;
  for (let hops = 0; node && hops < 3; hops += 1, node = node.return) {
    const debugSource = node._debugSource;
    if (debugSource?.fileName) {
      return {
        file: truncate(debugSource.fileName, 300),
        line: debugSource.lineNumber,
        column: debugSource.columnNumber,
      };
    }
    const debugStack = node._debugStack;
    const stack =
      typeof debugStack === "string"
        ? debugStack
        : debugStack instanceof Error
          ? debugStack.stack
          : undefined;
    if (stack) {
      const parsed = parseSourceFromStack(stack);
      if (parsed) return parsed;
    }
  }
  return undefined;
}

function readReactInfo(
  element: Element,
): Pick<SnagElement, "component" | "componentStack" | "source"> {
  try {
    const fiber = getFiber(element);
    if (!fiber) return {};
    const componentStack = readComponentStack(fiber);
    const source = readSource(fiber);
    return {
      component: componentStack[0],
      componentStack: componentStack.length > 0 ? componentStack : undefined,
      source,
    };
  } catch {
    return {};
  }
}

/** Snapshot everything an agent needs to find `element` in the codebase. */
export function describeElement(element: Element): SnagElement {
  const rect = element.getBoundingClientRect();
  return {
    selector: buildSelector(element),
    tag: element.tagName.toLowerCase(),
    text: readText(element),
    attributes: readAttributes(element),
    rect: {
      x: Math.round(rect.left),
      y: Math.round(rect.top),
      width: Math.round(rect.width),
      height: Math.round(rect.height),
    },
    ...readReactInfo(element),
  };
}

/** One-line label for chips and the picker tooltip. */
export function elementLabel(element: Pick<SnagElement, "tag" | "text" | "component">): string {
  const parts = [`<${element.tag}>`];
  if (element.text) parts.push(`"${truncate(element.text, 32)}"`);
  if (element.component) parts.push(`· ${element.component}`);
  return parts.join(" ");
}
